version: '3.7'

services:
  db:
    image: postgres:15.0
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - "8000:8001"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
