version: '3.7'

services:
  db:
    image: postgres:15-bookworm
    container_name: db
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always

  django:
    build: .
    expose:
      - 8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    container_name: django
    volumes:
      - ./django_chat/debug.log:/home/chat/django_chat/debug.log
    restart: always

  redis:
    image: redis:7.2.4-bookworm
    env_file:
      - .env
    expose:
      - 6379
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./django_chat/static:/static:ro
    depends_on:
      - django

volumes:
  postgres_data:
